# Generated by Django 4.1.3 on 2022-12-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('muscles', models.CharField(max_length=128)),
                ('equipment', models.CharField(max_length=128)),
                ('aType', models.CharField(choices=[('AN', 'Anaerobic'), ('AR', 'Aerorobic')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Weeks_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sets', models.IntegerField(default=3)),
                ('reps_per_set', models.IntegerField(default=6)),
                ('weight_lifted', models.IntegerField(default=10)),
                ('duration_seconds', models.TimeField(default='00:12:30')),
                ('average_speed_mph', models.FloatField(default=7.2)),
                ('miles_traveled', models.FloatField(default=1.5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_workout', models.DateField(verbose_name='time of workout')),
                ('goal_met', models.BooleanField(default=False)),
                ('number_of_sets', models.IntegerField(default=1)),
                ('reps_per_set', models.IntegerField(default=1)),
                ('weight_lifted', models.IntegerField(default=5)),
                ('duration', models.TimeField(default='00:12:30')),
                ('average_speed', models.FloatField(default=6.0)),
                ('distance_traveled', models.FloatField(default=1.5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('goal_workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout_goal')),
            ],
        ),
        migrations.CreateModel(
            name='Days_workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met_day_goals', models.BooleanField(default=False)),
                ('met_day_goals_percent', models.IntegerField(default=0)),
                ('actual_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout_actual')),
                ('goal_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout_goal')),
            ],
        ),
    ]
