# Generated by Django 4.1.3 on 2022-12-08 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='workout_actual',
            old_name='duration',
            new_name='duration_seconds',
        ),
        migrations.RenameField(
            model_name='workout_actual',
            old_name='distance_traveled',
            new_name='miles_traveled',
        ),
        migrations.RenameField(
            model_name='workout_actual',
            old_name='weight_lifted',
            new_name='weight_lifted_lbs',
        ),
        migrations.RemoveField(
            model_name='workout_actual',
            name='average_speed',
        ),
        migrations.AddField(
            model_name='workout_actual',
            name='average_speed_mph',
            field=models.FloatField(default=7.2),
        ),
        migrations.AddField(
            model_name='workout_actual',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout_goal',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
