# Generated by Django 4.1.3 on 2022-12-11 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout_actual',
            options={'ordering': ['-time_of_workout']},
        ),
        migrations.RemoveField(
            model_name='workout_actual',
            name='goal_workout_id',
        ),
        migrations.RemoveField(
            model_name='workout_goal',
            name='weight_lifted',
        ),
        migrations.AddField(
            model_name='workout_goal',
            name='weight_lifted_lbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='average_speed_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='duration_seconds',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='goal_met',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='number_of_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='reps_per_set',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='time_of_workout',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout_actual',
            name='weight_lifted_lbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_goal',
            name='average_speed_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_goal',
            name='duration_seconds',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_goal',
            name='miles_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_goal',
            name='number_of_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout_goal',
            name='reps_per_set',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
