# Generated by Django 4.1.3 on 2022-12-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_actual_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('workouts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout_actual')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Days_workout',
        ),
    ]
