# Generated by Django 4.1.3 on 2022-12-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_days_plan_delete_days_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weeks_plan',
        ),
        migrations.RemoveField(
            model_name='workout_goal',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout_goal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Workout_Program',
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='aType',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscles',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Workout_goal',
        ),
    ]
